routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Usuario
Auth::routes();
Route::resource('usuario','UserController');
Route::get('usuario/teste','HomeController@teste')->name('usuario.teste');
//Route::resource('login','LoginController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/','HomeController@index')->name('index');

//Instituicao
Route::resource('instituicao','InstituicaoController');
Route::get('datatable/instituicao', 'InstituicaoController@dataTableJson')->name('instituicao.datatable');

//Ativos
Route::resource('ativos','AtivosController');
Route::get('datatable/ativos', 'AtivosController@dataTableJson')->name('ativos.datatable');

//Endereços
Route::resource('enderecos','EnderecosController');

//Estados
Route::resource('estados','EstadosController');
Route::get('estados/{estado}','EstadosController@getCidades')->name('estado.cidade');

//Dividendos
Route::resource('dividendos','DividendosController');

//Produtos
Route::resource('produtos','ProdutosController');
Route::get('datatable/produtos', 'ProdutosController@dataTableJson')->name('produtos.datatable');

//IMPOSTO
Route::resource('imposto','ImpostoController');

//PDF PRODUTOS
Route::get('pdf/produtos','ProdutosController@gerarPDF')->name('pdf.produtos');

//PDF DIVIDENDOS
Route::get('pdf/dividendos','DividendosController@gerarPDF')->name('pdf.dividendos');

//PDF RENDIMENTOS
Route::get('pdf/rendimentos','HomeController@gerarPDF')->name('pdf.rendimentos');

app/Dividendos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dividendos extends Model
{
    protected $table= 'dividendos';
    protected $primaryKey= 'divCodigo';
    protected $fillable= ['divData', 'divValor', 'divTipo'];
}

app/Http/Controllers/DividendosController.php
<?php

namespace App\Http\Controllers;
use App\Dividendos;
use App\Produtos;
use Illuminate\Http\Request;
use App\Http\Requests\DividendosRequest;
use Illuminate\Support\Facades\DB;
use Auth;
use PDF;

class DividendosController extends Controller
{

    private $objDividendos;

    public function __construct(){
       $this-> objDividendos = new Dividendos;

        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produtos= Produtos:: join('dividendos as dividendos','dividendos.divCodigo','produtos.dividendos_divCodigo')
            ->join('ativos as at','at.atiCodigo','produtos.ativos_atiCodigo')
            ->select( DB::raw('sum( produtos.proQuantidade ) as Total, at.atiSigla, at.atiNome, dividendos.divCodigo, dividendos.divValor, dividendos.divData, dividendos.divTipo'))
            ->groupBy('produtos.ativos_atiCodigo')
            ->where('produtos.proOperacao', 1)
            ->where('users_id', Auth::user()->id)
            ->get();
    
        return view('dividendos.index',compact('produtos'));
        
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $produtos = Produtos::where('users_id', Auth::user()->id)
        //->where('dividendos_divCodigo', NULL)
        ->groupBy('ativos_atiCodigo')
        ->where('produtos.proOperacao', 1)
        ->get();
        return view('dividendos.create', compact('produtos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DividendosRequest $request)
    {
        $result = new Dividendos;
        $result->divData = $request->divData;
        $result->divValor = ((float) $request->divValor);
        $result->divTipo = $request->divTipo;
        $result->save();

        $produtos = Produtos::where('ativos_atiCodigo',$request->ativos_atiCodigo)
            ->update(['dividendos_divCodigo' => $result->divCodigo]);
        
        return redirect()->route('dividendos.index')
            ->withSuccess('Cadastro realizado!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dividendos= Dividendos:: find($id); //manda os dados dos dividendos OK

        $produtos = Produtos::where('users_id', Auth::user()->id)
        ->groupBy('ativos_atiCodigo')
        ->where('produtos.proOperacao', 1)
        ->get();// preenche o novo select OK

        $div = Produtos::where('dividendos_divCodigo', $id)
            ->join('ativos as ativos','produtos.ativos_atiCodigo','ativos.atiCodigo')
            ->where('produtos.users_id',Auth::user()->id)
            ->get(); //preenche com o ativo já selecionado

        return view('dividendos.update', compact('produtos', 'div', 'dividendos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DividendosRequest $request, $id)
    {
        //recebe cod dividendo
        $this->objDividendos->where(['divCodigo'=>$id])->update([
            'divData' => $request->divData,
            'divValor' =>((float) $request->divValor),
            'divTipo' =>$request->divTipo,
        ]);

        $produtos= Produtos:: where('dividendos_divCodigo', $id)
            ->update(['dividendos_divCodigo' => NULL]);

        $produtos2= Produtos::where('ativos_atiCodigo',$request->ativos_atiCodigo)
            ->update(['dividendos_divCodigo' => $id]);

        return redirect()->route('dividendos.index')
        ->withSuccess('Alteração realizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produtos= Produtos:: where('dividendos_divCodigo', $id)
            ->update(['dividendos_divCodigo' => NULL]);

        $dividendos = Dividendos::find($id);
        if ( $dividendos == null) {
            return response()->json(false);
        }
        $dividendos->delete();
        return response()->json(true);
    }

    public function gerarPDF(){

        $data = date("d/m/Y");
        $data = explode("/", $data);
        list($dia, $mes, $ano) = $data;

        if($mes == 1){ $mes="janeiro"; }
        if($mes == 2){ $mes="fevereiro"; }
        if($mes == 3){ $mes="março"; }
        if($mes == 4){ $mes="abril"; }
        if($mes == 5){ $mes="maio"; }
        if($mes == 6){ $mes="junho"; }
        if($mes == 7){ $mes="julho"; }
        if($mes == 8){ $mes="agosto"; }
        if($mes == 9){ $mes="setembro"; }
        if($mes == 10){ $mes="outubro"; }
        if($mes == 11){ $mes="novembro"; }
        if($mes == 12){ $mes="dezembro"; }

        $data= "$dia de $mes de $ano";

        $produtos= Produtos:: join('dividendos as dividendos','dividendos.divCodigo','produtos.dividendos_divCodigo')
            ->join('ativos as at','at.atiCodigo','produtos.ativos_atiCodigo')
            ->select( DB::raw('sum( produtos.proQuantidade ) as Total, at.atiSigla, at.atiNome, dividendos.divCodigo, dividendos.divValor, dividendos.divData, dividendos.divTipo'))
            ->groupBy('produtos.ativos_atiCodigo')
            ->where('produtos.proOperacao', 1)
            ->where('users_id', Auth::user()->id)
            ->get();

        $dividendos= Produtos:: join('dividendos as dividendos','dividendos.divCodigo','produtos.dividendos_divCodigo')
            ->select( DB::raw('sum( produtos.proQuantidade ) as Total, dividendos.divValor'))
            ->where('produtos.proOperacao', 1)
            ->where('users_id', Auth::user()->id)
            ->get();

        $Total= 0;
        $Calculo = 0;
    
        foreach($dividendos as $dividendos){
            $Soma= $Total;
            $Calculo= $dividendos->divValor * $dividendos->Total;
            $Total= $Soma + $Calculo ; 
        }

        $pdf = PDF::loadView('dividendos.pdf', compact('produtos', 'data', 'Total', )); //espera uma view

        return $pdf->setPaper('a4')->stream('dividendos.pdf');
    }
}

resources/views/dividendos/create.blade.php
@extends('layouts.master')

@section('body')

<div class="row border-bottom border-secondary rounded-bottom p-3 shadow-sm">
    <img src="{{ asset('img/barras.png')}}" alt="Ações" height="40px" width="40px" class="mr-3">
    <h2 class="text-secondary">Cadastrar Novo Dividendo ou JSCP</h2>
</div>
    <br><br>

<div>
    <form name="formPro" id="formPro" method="POST" action="{{url('dividendos')}}"> <!--Manda pro store do controller-->
        @csrf
        <div class="row"> 
            <div class="w-25 ml-5">
                <div class="form-group ">
                    <label class="text-secondary required">Ativo:</label>
                    <select class="form-control border rounded" name="ativos_atiCodigo" id="ativos_atiCodigo" required>
                        <Option value="">Selecione o ativo</Option>
                        @foreach($produtos as $produtos)
                            <option value="{{ $produtos->ativos->atiCodigo}}" >{{ $produtos->ativos->atiSigla }} - {{$produtos->ativos->atiNome}}</option>    
                        @endforeach
                    </select>
                    @if($errors->get('ativos_atiCodigo'))
                        @foreach($errors->get('ativos_atiCodigo') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <div class="form-group">
                    <label class="text-secondary required">Data:</label>
                    <input type="date" class="form-control border rounded" id="divData" name = "divData" placeholder="Insira a data??" required>
                    @if($errors->get('divData'))
                        @foreach($errors->get('divData') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
            </div>
            <div class="w-25 ml-5">
                <div class="form-group">
                    <label class="text-secondary required">Valor por ação:</label>
                    <input type="text" class="form-control border rounded" id="divValor" name = "divValor" placeholder="Insira o valor por ação" required>
                    @if($errors->get('divValor'))
                        @foreach($errors->get('divValor') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <div class="form-group">
                    <label class="text-secondary required">Tipo:</label>
                    <select class="form-control border rounded" name="divTipo" id="divTipo" required>
                        <Option value="">Selecione o tipo</Option>
                        <option value="Dividendo">Dividendo</option>
                        <option value="JSCP">JSCP</option>
                    </select>
                    @if($errors->get('divTipo'))
                        @foreach($errors->get('divTipo') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <!--<input type="hidden"  name="users_id" id="users_id" value="{{ Auth::user()->id }}">-->
            </div>
            <div class="w-25 ml-5">
                <div class="mt-4">
                        <button type="submit" class="btn btn-success mt-auto w-100">Cadastrar</button>
                        <br><br><br>
                        <a href="{{ route('dividendos.index') }}" class="btn btn-dark w-100">
                            Cancelar
                        </a>
                </div>
            </div>
        </div>

        <div class="ml-5">
            <br>
            <label for="" class="required text-danger"> Campos Obrigatórios: </label>
        </div>
    </form>
</div>

@endSection

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>


<script type="text/javascript">
    jQuery(function($){
            $("#divValor").mask('##0.00', {reverse: true});
    });
</script>

resources/views/dividendos/index.blade.php
@extends('layouts.master')

@section('body')

<!--Mensagem success-->
@if(Session::has('success'))
	<div class="alert alert-success alert-dimissible fade show">
		{{ Session::get('success') }}
		<button type="button" class="close" data-dismiss='alert' arial-label="Close">
			<span aria-hidden = "true"> &times; </span>
		</button>
	</div>
@endIF

<!--CABEÇALHO-->
<div class="row border-bottom border-secondary rounded-bottom p-3 shadow-sm">
    <img src="{{ asset('img/barras.png')}}" alt="Ações" height="40px" width="40px" class="mr-3">
    <h2 class="text-secondary">Dividendos e JSCP</h2>
    <a class="ml-auto mr-2" href="{{ route('dividendos.create') }}">
        <button class="btn btn-success">
            Cadastrar
        </button>
    </a>
    <a class="mr-2" href="{{ route('pdf.dividendos') }}">
        <button class="btn btn-dark text-light">
            PDF
        </button>
    </a>
</div>

<br><br>

<!--TABELA-->
<div class="">
        <table class="table table-dark text-dark" id="produtos-table">
            <thead>
                <tr>
                    <th class="text-light">Ação</th>
                    <th class="text-light">Tipo</th>
                    <th class="text-light">Valor por ação </th>
                    <th class="text-light">Valor </th>
                    <th class="text-light">Data </th>
                    <th class="text-light">Opções </th>
                </tr>
                <tbody>
                    @foreach ($produtos as $produtos)
                        <tr>
                            <td>{{$produtos->atiSigla}}</td>
                            <td>{{$produtos->divTipo}}</td>
                            <td>R${{$produtos->divValor}}</td>
                            <td>R${{$produtos->divValor * $produtos->Total}}</td>
                            <td> <input  class="border-0 bg-white text-dark" type="date" disabled="disabled" value="{{$produtos->divData}}"></td>
                            <td>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <a href="{{ route('dividendos.edit', $produtos->divCodigo) }}" class="btn btn-primary" style="height:40px;">
                                            <i class="fa fa-edit mr-1"></i>
                                            Editar
                                        </a>
                                    </div>
                                    <div class="col-lg-6">
                                        <button type="button" class="btn btn-danger" style="height:40px;" data-toggle="modal" data-target="#modalExcluir" onclick="abrirModal('{{$produtos->divCodigo}}')"> 
                                            <i class="fa fa-trash-o mr-2"></i>
                                            Apagar
                                        </button>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </thead>
        </table>
</div>


<!--MODAL-->
<div class="modal fade" tabindex="-1" role="dialog" id="modalExcluir">
        <div class="modal-dialog border rounded" role="document">
            <div class="modal-content border rounded">
                <div class="modal-header bg-danger" style="height:50px;">
                    <h5 class="modal-title text-light align-center">ALERTA!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <input type="hidden" id="codigo">
                <div class="modal-body bg-light">
                        <span>Deseja</span>
                        <span class="text-danger">excluir</span>
                        <span>o item selecionado?</span>
                        <p id="modalBody"> </p>
                </div>
                <div class="modal-footer bg-light">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-danger" onclick="excluir()">Excluir</button>
                </div>
            </div>
        </div>
</div>

@endSection


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script type="text/javascript">

    jQuery(function() {
                jQuery('#produtos-table').DataTable({ 
                    dom: 'lBfrtip',
                    "language": {
                        "url": "http://cdn.datatables.net/plug-ins/1.10.15/i18n/Portuguese-Brasil.json"
                    },
                    buttons: [
                        'pdfHtml5',
                        'excelHtml5'
                    ]
                });
    });

    function abrirModal(id) {
        var divCodigo= id;
        console.log(divCodigo);
        $.ajax({
            type:'GET',
            url:'dividendos',
            headers:{
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            cache: false,
                error: function(response) {
                    console.log("Erro:\n"+response);
                },
                success: function(resposta) {
                    if(resposta != 'Vazio'){
                        codigo.value = divCodigo;
                        //modalBody.innerHTML = "Deseja excluir o item selecionado?";
                        $('#modalExcluir').modal('show');
                    } else {
                        alert('Não é possível realizar a exclusão');
                    }
                }
        });
    }

    function excluir(){        
        var divCodigo = codigo.value;
        console.log(divCodigo);

        $.ajax({
            type:'DELETE',
            url: 'dividendos/'+divCodigo,
            //data: "{}",
            //contentType: "application/json; charset=utf-8",
            //dataType: "json",
            headers:{
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                'Content-type': 'application/json',
                'Authorization': '${this.state.tokenType} ${this.state.token}' 
            },
            cache: false,
                error: function(response) {
                    console.log("Erro:\n"+response);
                },
                success: function(resposta) {
                    if(resposta == true){
                        $('#modalExcluir').modal('hide');
                        console.log("ok");
                        window.location.assign('dividendos');
                    } else {
                        alert('Não é possível realizar a exclusão');
                    }
                }
        }); 
    }

  </script>

resources/views/dividendos/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">  
    <link href="{{ asset('img/logoMini.png') }}" rel="icon">

</head>
<body>

    <div class="w-100" >
        <img src="{{ asset('img/LOGO.png')}}" alt="Logo" height="60px" width="150px" style="margin-left:270px">
        <br>
        <h5 style="margin-left:200px" class="mt-4">Relatório de Dividendos e JSPC</h5>
    </div>
    <br>
    <div class="p-2">
        <label for="" class="ml-2">Seus dividendos e JSPC:</label>
        <br>
        <table class="table ml-3 mr-3 border">
        <thead>
                    <tr>
                        <th class="border" style="font-size: 13px">Ação</th>
                        <th class="border" style="font-size: 13px">Tipo</th>
                        <th class="border" style="font-size: 13px">Valor por ação </th>
                        <th class="border" style="font-size: 13px">Valor </th>
                        <th class="border" style="font-size: 13px">Data </th>
                    </tr>
                    <tbody>
                        @foreach ($produtos as $produtos)
                            <tr>
                                <td class="border" style="font-size: 13px">{{$produtos->atiSigla}}</td>
                                <td class="border" style="font-size: 13px">{{$produtos->divTipo}}</td>
                                <td class="border" style="font-size: 13px">R${{$produtos->divValor}}</td>
                                <td class="border" style="font-size: 13px">R${{$produtos->divValor * $produtos->Total}}</td>
                                <td class="border" style="font-size: 13px">{{$produtos->divData}}</td>
                            </tr>
                        @endforeach
                    </tbody>
            </thead>
        </table>
        <label for="" class="ml-2">Valor total: R${{$Total}} </label>
    
    </div>
    <br><br>

    <div class="ml-3 mr-3">
        <label for="" style="margin-left:280px">{{$data}}</label>
    </div>
</body>
</html>

resources/views/dividendos/update.blade.php
@extends('layouts.master')

@section('body')

<div class="row border-bottom border-secondary rounded-bottom p-3 shadow-sm">
    <img src="{{ asset('img/barras.png')}}" alt="Ações" height="40px" width="40px" class="mr-3">
    <h2 class="text-secondary">Editar {{ $dividendos->divTipo }}</h2>
</div>
    <br><br>

<div>
    <form name="formPro" id="formPro" method="POST" action="{{ route('dividendos.update', $dividendos->divCodigo) }}">
        @method('PUT')
        @csrf
        <div class="row"> 
            <div class="w-25 ml-5">
                <div class="form-group ">
                    <label class="text-secondary required">Ativo:</label>
                    <select class="form-control border rounded" name="ativos_atiCodigo" id="ativos_atiCodigo" required>
                        @foreach ($div as $div)
                            <Option value="{{ $div->atiCodigo }}" class="bg-secondary text-light"> {{ $div->atiSigla}} - {{ $div->atiNome}}</Option>
                        @endforeach
                        @foreach($produtos as $produtos)
                            <option value="{{ $produtos->ativos->atiCodigo}}" >{{ $produtos->ativos->atiSigla }} - {{$produtos->ativos->atiNome}}</option>
                        @endforeach
                    </select>
                    @if($errors->get('ativos_atiCodigo'))
                        @foreach($errors->get('ativos_atiCodigo') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <div class="form-group">
                    <label class="text-secondary required">Data:</label>
                    <input type="date" class="form-control border rounded" id="divData" name = "divData" placeholder="Insira a data??" required value="{{ $dividendos->divData}}">
                    @if($errors->get('divData'))
                        @foreach($errors->get('divData') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
            </div>
            <div class="w-25 ml-5">
                <div class="form-group">
                    <label class="text-secondary required">Valor por ação:</label>
                    <input type="text" class="form-control border rounded" id="divValor" name = "divValor" placeholder="Insira o valor por ação" required value="{{ $dividendos->divValor}}">
                    @if($errors->get('divValor'))
                        @foreach($errors->get('divValor') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <div class="form-group">
                    <label class="text-secondary ml-3">Tipo:</label>
                    <select class="form-control border rounded" name="divTipo" id="divTipo" required>
                        <Option value="{{ $dividendos->divTipo }}" class="bg-secondary text-light"> {{ $dividendos->divTipo }}</Option>
                        <option value="Dividendo">Dividendo</option>
                        <option value="JSCP">JSCP</option>
                    </select>
                    @if($errors->get('divTipo'))
                        @foreach($errors->get('divTipo') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <!--<input type="hidden"  name="users_id" id="users_id" value="{{ Auth::user()->id }}">-->
            </div>
            <div class="w-25 ml-5">
                <div class="mt-4">
                        <button type="submit" class="btn btn-success mt-auto w-100">Salvar</button>
                        <br><br><br>
                        <a href="{{ route('dividendos.index') }}" class="btn btn-dark w-100">
                            Cancelar
                        </a>
                </div>
            </div>
        </div>

        <div class="ml-5">
            <br>
            <label for="" class="required text-danger"> Campos Obrigatórios: </label>
        </div>
    </form>
</div>

@endSection

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>


<script type="text/javascript">
    jQuery(function($){
            $("#divValor").mask('#.##0.00', {reverse: true});
    });
</script>