routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Usuario
Auth::routes();
Route::resource('usuario','UserController');
Route::get('usuario/teste','HomeController@teste')->name('usuario.teste');
//Route::resource('login','LoginController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/','HomeController@index')->name('index');

//Instituicao
Route::resource('instituicao','InstituicaoController');
Route::get('datatable/instituicao', 'InstituicaoController@dataTableJson')->name('instituicao.datatable');

//Ativos
Route::resource('ativos','AtivosController');
Route::get('datatable/ativos', 'AtivosController@dataTableJson')->name('ativos.datatable');

//Endereços
Route::resource('enderecos','EnderecosController');

//Estados
Route::resource('estados','EstadosController');
Route::get('estados/{estado}','EstadosController@getCidades')->name('estado.cidade');

//Dividendos
Route::resource('dividendos','DividendosController');

//Produtos
Route::resource('produtos','ProdutosController');
Route::get('datatable/produtos', 'ProdutosController@dataTableJson')->name('produtos.datatable');

//IMPOSTO
Route::resource('imposto','ImpostoController');

//PDF PRODUTOS
Route::get('pdf/produtos','ProdutosController@gerarPDF')->name('pdf.produtos');

//PDF DIVIDENDOS
Route::get('pdf/dividendos','DividendosController@gerarPDF')->name('pdf.dividendos');

//PDF RENDIMENTOS
Route::get('pdf/rendimentos','HomeController@gerarPDF')->name('pdf.rendimentos');

app/Produtos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;

class Produtos extends Model
{
    protected $table= 'produtos';
    protected $primaryKey= 'proCodigo';
    protected $fillable= ['proData', 'proQuantidade','proPreco','proTaxa','proOperacao','ativos_atiCodigo','users_id','instituicao_insCodigo', 'dividendos_divCodigo'];

    public function ativos(){
        return $this->belongsTo('App\Ativos', 'ativos_atiCodigo', 'atiCodigo');
    }

    public function user(){
        return $this->belongsTo('App\User', 'users_id', 'id');
    }

    public function instituicao(){
        return $this->belongsTo('App\Instituicao', 'instituicao_insCodigo', 'insCodigo');
    }
    public function dividendos(){
        return $this->belongsTo('App\Dividendos', 'dividendos_divCodigo', 'divCodigo');
    }
}

app/Http/Controllers/ProdutosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Produtos;
use App\Ativos;
use App\Http\Requests\ProdutosRequest;
use Illuminate\Support\Facades\DB;
use Auth;
use PDF;
Use \Carbon\Carbon;

class ProdutosController extends Controller
{

    private $objProdutos;

    public function __construct(){
        $this-> objProdutos = new Produtos;

        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produtos = Produtos::where('users_id', Auth::user()->id)->get();
        return view('produtos.index',['produtos'=>$produtos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ativos = DB::table('ativos')->orderBy('atiNome', 'asc')
         ->get();

        $instituicao = DB::table('instituicao')->orderBy('insNome', 'asc')
         ->get();

        return view('produtos.create', compact('ativos', 'instituicao'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProdutosRequest $request)
    {
        //Operação = 1-Compra 2-Venda
        $cadastro = $this->objProdutos->create([
            'proData' =>$request->proData,
            'proQuantidade' =>$request->proQuantidade,
            'proPreco' => ((float) $request->proPreco),
            'proTaxa' =>$request->proTaxa,
            'proOperacao' =>$request->proOperacao,
            'ativos_atiCodigo' =>$request->ativos_atiCodigo,
            'users_id' =>$request->users_id,
            'instituicao_insCodigo' =>$request->instituicao_insCodigo
        ]);
        if($cadastro){
            return redirect()->route('produtos.index')
            ->withSuccess('Compra de ativo registrada!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $produtos = $this->objProdutos->find($id);
        return view('produtos.show', compact('produtos'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ativos = DB::table('ativos')->orderBy('atiNome', 'asc')
         ->get();

        $instituicao = DB::table('instituicao')->orderBy('insNome', 'asc')
         ->get();

        $produtos = $this->objProdutos->find($id);

        return view('produtos.update', compact('produtos', 'ativos','instituicao'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProdutosRequest $request, $id)
    {
        //Operação = 1-Compra 2-Venda
        $cadastro = $this->objProdutos->where(['proCodigo'=>$id])->update([
            'proData' =>$request->proData,
            'proQuantidade' =>$request->proQuantidade,
            'proPreco' => ((float) $request->proPreco),
            'proTaxa' =>$request->proTaxa,
            'proOperacao' =>$request->proOperacao,
            'ativos_atiCodigo' =>$request->ativos_atiCodigo,
            'users_id' =>$request->users_id,
            'instituicao_insCodigo' =>$request->instituicao_insCodigo
        ]);
        if($cadastro){
            return redirect()->route('produtos.index')
            ->withSuccess('Ativo alterado com sucesso!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produtos = Produtos:: find($id);
        $produtos->delete();

        return redirect()->route('produtos.index');
    }

    public function dataTableJson(){
        return response()->json(['data'=>Produtos::where('users_id', Auth::user()->id)->with('ativos')->get()]);
    }

    public function gerarPDF(){
        
        $data = date("d/m/Y");
        $data = explode("/", $data);
        list($dia, $mes, $ano) = $data;

        if($mes == 1){ $mes="janeiro"; }
        if($mes == 2){ $mes="fevereiro"; }
        if($mes == 3){ $mes="março"; }
        if($mes == 4){ $mes="abril"; }
        if($mes == 5){ $mes="maio"; }
        if($mes == 6){ $mes="junho"; }
        if($mes == 7){ $mes="julho"; }
        if($mes == 8){ $mes="agosto"; }
        if($mes == 9){ $mes="setembro"; }
        if($mes == 10){ $mes="outubro"; }
        if($mes == 11){ $mes="novembro"; }
        if($mes == 12){ $mes="dezembro"; }

        $data= "$dia de $mes de $ano";

        $produtosC= Produtos::where('users_id', Auth::user()->id)
        ->where('proOperacao',1)->get();

        $produtosV= Produtos::where('users_id', Auth::user()->id)
        ->where('proOperacao',2)->get();

        $produtos= Produtos::where('users_id', Auth::user()->id)->get();

        $TotalCompras= 0;
        $Calculo = 0;

        foreach($produtosC as $produtosC){
            $Soma= $TotalCompras;
            $Calculo= $produtosC->proQuantidade * $produtosC->proPreco;
            $TotalCompras= $Soma + $Calculo ; 
        }

        $TotalVendas= 0;
        $Calculo2 = 0;

        foreach($produtosV as $produtosV){
            $Soma= $TotalVendas;
            $Calculo2= $produtosV->proQuantidade * $produtosV->proPreco;
            $TotalVendas= $Soma + $Calculo2 ;   
        }
        
        $pdf = PDF::loadView('produtos.pdf', compact('produtos','data', 'TotalCompras', 'TotalVendas')); //espera uma view

        return $pdf->setPaper('a4')->stream('ativos.pdf');
    }


}

resources/views/produtos/create.blade.php
@extends('layouts.master')

@section('body')

<div class="row border-bottom border-secondary rounded-bottom p-3 shadow-sm">
    <img src="{{ asset('img/barras.png')}}" alt="Ações" height="40px" width="40px" class="mr-3">
    <h2 class="text-secondary">Registrar Operação</h2>
</div>
    <br><br>

<div>
    <form name="formPro" id="formPro" method="POST" action="{{url('produtos')}}"> <!--Manda pro store do controller-->
        @csrf
        <div class="row"> 
            <div class="w-25 ml-5">
                <div class="form-group ">
                    <label class="text-secondary required">Instituição Financeira:</label>
                    <select class="form-control border rounded" name="instituicao_insCodigo" id="instituicao_insCodigo" required>
                        <Option value="">Selecione a Instituição Financeira</Option>
                        @foreach($instituicao as $instituicao)
                            <option value="{{ $instituicao->insCodigo}}" >{{ $instituicao->insNome }}</option>
                        @endforeach
                    </select>
                    @if($errors->get('instituicao_insCodigo'))
                        @foreach($errors->get('instituicao_insCodigo') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <div class="form-group">
                    <label class="text-secondary required">Ativo:</label>
                    <select class="form-control border rounded" name="ativos_atiCodigo" id="ativos_atiCodigo" required>
                        <Option value="">Selecione o Ativo</Option>
                        @foreach($ativos as $ativos)
                            <option value="{{ $ativos->atiCodigo}}" >{{ $ativos->atiSigla }} - {{ $ativos->atiNome}}</option>
                        @endforeach
                    </select>
                    @if($errors->get('ativos_atiCodigo'))
                        @foreach($errors->get('ativos_atiCodigo') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <div class="form-group">
                    <label class="text-secondary required">Operação:</label>
                    <select name="proOperacao" id="proOperacao" class="form-control border rounded" required>
                        <option>Selecione a Operação</option>
                        <option value="1">Compra</option>
                        <option value="2">Venda</option>
                    </select>
                    @if($errors->get('proOperacao'))
                        @foreach($errors->get('proOperacao') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
            </div>
            <div class="w-25 ml-5">
                <div class="form-group">
                    <label class="text-secondary required">Preço:</label>
                    <input type="text" class="form-control border rounded" id="proPreco" name = "proPreco" placeholder="Insira o preço de compra da ação" required>
                    @if($errors->get('proPreco'))
                        @foreach($errors->get('proPreco') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <div class="form-group">
                    <label class="text-secondary required">Quantidade:</label>
                    <input type="text" class="form-control border rounded" id="proQuantidade" name = "proQuantidade" placeholder="Insira a quantidade comprada" required>
                    @if($errors->get('proQuantidade'))
                        @foreach($errors->get('proQuantidade') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                <div class="form-group">
                    <div class="row">
                        <label class="text-secondary ml-3">Taxas:</label>
                        <label for="" class="text-secondary ml-1 mt-1" style="font-size:13px">
                            (corretagem + emolumentos + liquidação)
                        </label>
                    </div>
                    <input type="text" class="form-control border rounded" id="proTaxa" name = "proTaxa" placeholder="Insira a taxa">
                </div>
                <input type="hidden"  name="users_id" id="users_id" value="{{ Auth::user()->id }}">
            </div>
            <div class="w-25 ml-5">
                <div class="form-group">
                    <label class="text-secondary required">Data:</label>
                    <input type="date" class="form-control border rounded" id="proData" name = "proData" placeholder="Insira a data da compra da ação" required>
                    @if($errors->get('proData'))
                        @foreach($errors->get('proData') as $error)
                            <span class="text-danger">{{ $error }}</span>
                        @endForeach
                    @endIF
                </div>
                

                <div class="mt-5">
                        <button type="submit" class="btn btn-success mt-auto w-100">Cadastrar</button>
                        <br><br><br>
                        <a href="{{ route('produtos.index') }}" class="btn btn-dark w-100">
                            Cancelar
                        </a>
                </div>
            </div>
        </div>

        <div class="ml-5">
            <br>
            <label for="" class="required text-danger"> Campos Obrigatórios: </label>
        </div>
    </form>
</div>

@endSection

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>


<script type="text/javascript">
    jQuery(function($){
            $("#proPreco").mask('##0.00', {reverse: true});
            $("#proTaxa").mask('##0.00', {reverse: true});
    });
</script>

resources/views/produtos/index.blade.php
@extends('layouts.master')

@section('body')

<!--Mensagem success-->
@if(Session::has('success'))
	<div class="alert alert-success alert-dimissible fade show">
		{{ Session::get('success') }}
		<button type="button" class="close" data-dismiss='alert' arial-label="Close">
			<span aria-hidden = "true"> &times; </span>
		</button>
	</div>
@endIF

<!--CABEÇALHO-->
<div class="row border-bottom border-secondary rounded-bottom p-3 shadow-sm">
    <img src="{{ asset('img/barras.png')}}" alt="Ações" height="40px" width="40px" class="mr-3">
    <h2 class="text-secondary">Ações Compradas e Vendidas</h2>
    <a class="ml-auto mr-2" href="{{ route('produtos.create') }}">
        <button class="btn btn-success">
            Registrar Operação
        </button>
    </a>
    <a class="mr-2" href="{{ route('pdf.produtos') }}">
        <button class="btn btn-dark text-light">
            PDF
        </button>
        <!-- Quando clicar aqui tem que gerar o pdf-->
    </a>
</div>

<br><br>

<!--TABELA-->
<div class="">
        <table class="table table-dark text-dark" id="produtos-table">
            <thead>
                <tr>
                    <th class="text-light">Operação</th>
                    <th class="text-light">Ação</th>
                    <th class="text-light">Quantidade </th>
                    <th class="text-light">Valor </th>
                    <th class="text-light">Total </th>
                    <th class="text-light">Opções </th>
                </tr>
                <tbody>
                    @foreach ($produtos as $pro)
                        <tr>
                            <input type="hidden" value="{{$pro->proCodigo}}" name="proCodigo" id="proCodigo">
                            @if($pro->proOperacao==1)
                                <td>Compra</td>
                            @else ($pro->proOperacao==2)
                                <td>Venda</td>
                            @endif
                            <td>{{$pro->ativos->atiSigla}}</td>
                            <td>{{$pro->proQuantidade}}</td>
                            <td>R${{$pro->proPreco}}</td>
                            <td>R${{$pro->proQuantidade * $pro->proPreco}}</td>
                            <td>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <a href="{{ route('produtos.show',$pro->proCodigo) }}" class="btn btn-dark" style="height:40px;">
                                            Visualizar
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </thead>
        </table>
</div>
@endSection


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script type="text/javascript">

    jQuery(function() {
                jQuery('#produtos-table').DataTable({ 
                    dom: 'lBfrtip',
                    "language": {
                        "url": "http://cdn.datatables.net/plug-ins/1.10.15/i18n/Portuguese-Brasil.json"
                    },
                    buttons: [
                        'pdfHtml5',
                        'excelHtml5'
                    ]
                });
    });

  </script>

resources/views/produtos/pdf.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">  
    <link href="{{ asset('img/logoMini.png') }}" rel="icon">

</head>
<body>

    <div class="w-100" >
        <img src="{{ asset('img/LOGO.png')}}" alt="Logo" height="60px" width="150px" style="margin-left:280px">
        <br>
        <h5 style="margin-left:170px" class="mt-4">Relatório de investimentos em renda variável</h5>
    </div>
    <br>
    <div class="p-2">
        <label for="" class="ml-2">Ações compradas:</label>
        <br>
        <table class="table ml-3 mr-3 border">
        <thead>
                    <tr>
                        <th class="border" style="font-size: 13px">Ação</th>
                        <th class="border" style="font-size: 13px">Instituição Financeira</th>
                        <th class="border" style="font-size: 13px">Data</th>
                        <th class="border" style="font-size: 13px">Quantidade </th>
                        <th class="border" style="font-size: 13px">Valor </th>
                        <th class="border" style="font-size: 13px">Taxa </th>
                        <th class="border" style="font-size: 13px">Total </th>
                    </tr>
                    <tbody>
                        @foreach ($produtos as $pro)
                            @if($pro->proOperacao==1)
                                <tr>
                                    <td class="border" style="font-size: 13px">{{$pro->ativos->atiSigla}} - {{$pro->ativos->atiNome}}</td>
                                    <td class="border" style="font-size: 13px">{{$pro->instituicao->insNome}}</td>
                                    <td class="border" style="font-size: 13px" type="date">{{$pro->proData}}</td>
                                    <td class="border" style="font-size: 13px">{{$pro->proQuantidade}}</td>
                                    <td class="border" style="font-size: 13px">R${{$pro->proPreco}}</td>
                                    @if($pro->proTaxa==NULL)
                                        <td class="border" style="font-size: 13px"> - </td>
                                    @else
                                        <td class="border" style="font-size: 13px">R${{$pro->proTaxa}}</td>
                                    @endif
                                    <td class="border" style="font-size: 13px"> R${{$pro->proQuantidade * $pro->proPreco}}</td>
                                </tr>
                            @endif
                        @endforeach
                    </tbody>
            </thead>
        </table>
        <label for="" class="ml-2">Valor total: R${{ $TotalCompras}}</label>
    
    </div>
    <br><br>
    <div class="p-2">
        <label for="" class="ml-2">Ações vendidas:</label>
        <br>

        <table class="table ml-3 mr-3 border">
            <thead>
                    <tr>
                        <th class="border" style="font-size: 13px">Ação</th>
                        <th class="border" style="font-size: 13px">Instituição Financeira</th>
                        <th class="border" style="font-size: 13px">Data</th>
                        <th class="border" style="font-size: 13px">Quantidade </th>
                        <th class="border" style="font-size: 13px">Valor </th>
                        <th class="border" style="font-size: 13px">Taxa </th>
                        <th class="border" style="font-size: 13px">Total </th>
                    </tr>
                    <tbody>
                        @foreach ($produtos as $pro)
                            @if($pro->proOperacao==2)
                                <tr>
                                    <td class="border" style="font-size: 13px">{{$pro->ativos->atiSigla}} - {{$pro->ativos->atiNome}}</td>
                                    <td class="border" style="font-size: 13px">{{$pro->instituicao->insNome}}</td>
                                    <td class="border" style="font-size: 13px" type="date">{{$pro->proData}}</td>
                                    <td class="border" style="font-size: 13px">{{$pro->proQuantidade}}</td>
                                    <td class="border" style="font-size: 13px">R${{$pro->proPreco}}</td>
                                    @if($pro->proTaxa==NULL)
                                        <td class="border" style="font-size: 13px"> - </td>
                                    @else
                                        <td class="border" style="font-size: 13px">R${{$pro->proTaxa}}</td>
                                    @endif
                                    <td class="border" style="font-size: 13px"> R${{$pro->proQuantidade * $pro->proPreco}}</td>
                                </tr>
                            @endif
                        @endforeach
                    </tbody>
            </thead>
        
        
        </table>
        <label for="" class="ml-2">Valor total: R${{ $TotalVendas}}</label>
    
    </div>

    <div class="ml-3 mr-3">
        <label for="" style="margin-left:280px">{{$data}}</label>
    </div>
</body>
</html>

resources/views/produtos/show.blade.php
@extends('layouts.master')

@section('body')

<div class="row border-bottom border-secondary rounded-bottom p-3 shadow-sm">
    <img src="{{ asset('img/barras.png')}}" alt="Ações" height="40px" width="40px" class="mr-3">
    <h2 class="text-secondary">Visualizar {{$produtos->ativos->atiSigla }}</h2>
</div>
    <br><br>

<div>
<form name="formPro" id="formPro" method="POST" action=" ">
        @csrf
        <div class="row"> 
            <div class="w-25 ml-5">
                <div class="form-group ">
                    <label class="text-secondary">Instituição Financeira:</label>
                    <input disabled="disabled" class="form-control border rounded" id="instituicao_insCodigo" name = "instituicao_insCodigo" value="{{ $produtos->instituicao->insNome }}">
                </div>
                <div class="form-group">
                    <label class="text-secondary">Ativo:</label>
                    <input disabled="disabled" class="form-control border rounded" id="ativos_atiCodigo" name = "ativos_atiCodigo" value="{{ $produtos->ativos->atiSigla }} - {{ $produtos->ativos->atiNome }}">
                </div>
                <div class="form-group">
                    <label class="text-secondary">Operação:</label>
                    @if($produtos-> proOperacao==1)
                        <input disabled="disabled" class="form-control border rounded" id="proOperacao" name = "proOperacao" value="Compra">
                        @else
                            <input disabled="disabled" class="form-control border rounded" id="proOperacao" name = "proOperacao" value="Venda">
                    @endif
                </div>
            </div>
            <div class="w-25 ml-5">
                <div class="form-group">
                    <label class="text-secondary">Preço:</label>
                    <input disabled="disabled" class="form-control border rounded" id="proPreco" name = "proPreco" value="R${{ $produtos-> proPreco}}">
                </div>
                <div class="form-group">
                    <label class="text-secondary">Quantidade:</label>
                    <input disabled="disabled" class="form-control border rounded" id="proQuantidade" name = "proQuantidade" value="{{ $produtos-> proQuantidade }}">
                </div>
                <div class="form-group">
                    <div class="row">
                        <label class="text-secondary ml-3">Taxas:</label>
                        <label for="" class="text-secondary ml-1 mt-1" style="font-size:13px">
                           (corretagem + emolumentos + liquidação)
                        </label>
                    </div>
                    @if($produtos->proTaxa==NULL)
                        <input disabled="disabled" class="form-control border rounded" id="proTaxa" name = "proTaxa" value="Nenhuma taxa foi aplicada">
                    @else
                        <input disabled="disabled" class="form-control border rounded" id="proTaxa" name = "proTaxa" value="R${{ $produtos-> proTaxa}}">
                    @endif
                </div>
                <input type="hidden"  name="users_id" id="users_id" value="{{ Auth::user()->id }}">
            </div>
            <div class="w-25 ml-5">
                <div class="form-group">
                    <label class="text-secondary">Data:</label>
                    <input disabled="disabled" class="form-control border rounded" id="proData" name = "proData" value="{{ $produtos->proData }}" type="date">
                </div>
                <div class="mt-5">
                        <a href="{{ route('produtos.index') }}" class="btn btn-dark w-25 ml-4">
                            Voltar
                        </a>
                        <a href="{{ route('produtos.edit', $produtos->proCodigo) }}" class="btn btn-primary w-25 ml-1">
                            Editar
                        </a>
                        <a href=" " class="btn btn-danger w-25 ml-1" data-toggle="modal" data-target="#modalExcluir">
                            Excluir
                        </a>
                </div>

            </div>
        </div>
    </form>
</div>

   <!--MODAL-->
   <div class="modal fade" tabindex="-1" role="dialog" id="modalExcluir">
        <div class="modal-dialog border rounded" role="document">
            <div class="modal-content border rounded">
                <div class="modal-header bg-danger" style="height:50px;">
                    <h5 class="modal-title text-light align-center">ALERTA!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <input type="hidden" id="codigo">
                <div class="modal-body bg-light">
                        <span>Deseja</span>
                        <span class="text-danger">excluir</span>
                        <span>a ação?</span>
                        <p id="modalBody"> </p>
                </div>
                <div class="modal-footer bg-light" style="height:60px;">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
                    <form action="{{ route('produtos.destroy', $produtos-> proCodigo )}}" method="POST">
                    @method('DELETE')
                    @csrf
                        <button type="submit" class="btn btn-danger mt-3">Excluir</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endSection

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>